### ISSUE TITLE
Courses show wrong time period

### ISSUE THREAD

**Issue by engemkeres** [simonyiszk/schdesign-web#40]
A tanfolyamok időpontjait UTC+1 időzónában vettem fel Contentful-ban, de UTC-ben kerülnek kiírásra a weboldalon a `fix-courses-2` merge után. A Google Calender linkek viszont helyesen, UTC+1-ben veszik fel az eseményt. Egyelőre Contentful-on mindent odébbtoltam UTC+2-re, ~~hogy így a preview jó legyen~~ - ez nem volt jó hotfix tőlem, ugyanaz maradt a kiírt időpont.

Calendar link hozzáadása előtt:
![image](https://github.com/simonyiszk/schdesign-web/assets/100580144/34e07d9a-3903-43dd-8823-7afc3fef7ec3)

Calendar link hozzáadása után:
![image](https://github.com/simonyiszk/schdesign-web/assets/100580144/f2d64b19-f934-44fa-bed7-78f4eade760d)

**Comment by AndrisBorbas** [comment]
az vickes mert nekem local dev en jó

**Comment by AndrisBorbas** [comment]
tippre a next update rontotta el, hogy mostmár fixen serveren fut le a date creation

**Comment by AndrisBorbas** [comment]
Ugyanitt a prod deployment ki volt kapcsolva contentfulon, azt visszanyomtam
